//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongMach_Ver_1._0.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thuoc
    {
        public int ID_Thuoc { get; set; }
        public string tenThuoc { get; set; }
        public int loaiThuoc { get; set; }
        public decimal soLuongTon { get; set; }
        public decimal donGia { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Edited { get; set; }
        public bool IsDelete { get; set; }
    }
}
